#
# GNUmakefile for target DemoApp
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = DemoApp

DemoApp_OBJC_FILES = DemoApp/main.m \
	DemoApp/AppDelegate.m 

DemoApp_C_FILES = 

DemoApp_CPP_FILES = 

DemoApp_OBJCPP_FILES = 

DemoApp_HEADER_FILES = 

DemoApp_RESOURCE_FILES = DemoApp/Assets.xcassets \
	DemoApp/Base.lproj/MainMenu.xib \
	DemoAppInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./DemoApp 

ADDITIONAL_OBJC_LIBS += 

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make

#
# end - generated makefile
#
